# Generated by Django 3.0.8 on 2020-07-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('current_speed', models.IntegerField(default=0)),
                ('current_battery', models.IntegerField(default=100)),
            ],
        ),
    ]
